const bags = [
{ name: "bright gray", contain  : "2 bright gold bags, 5 dull lavender bags" },
{ name: "pale olive", contain  : "1 bright yellow bag, 1 mirrored salmon bag" },
{ name: "mirrored magenta", contain  : "4 shiny turquoise bags, 2 bright gold bags, 4 plaid fuchsia bags, 4 wavy lime bags" },
{ name: "shiny blue", contain  : "3 dim plum bags, 4 bright blue bags, 5 plaid fuchsia bags" },
{ name: "dotted beige", contain  : "5 faded bronze bags, 1 posh olive bag, 5 dark magenta bags, 2 plaid lime bags" },
{ name: "drab tomato", contain  : "4 faded fuchsia bags, 4 plaid beige bags, 4 clear red bags" },
{ name: "drab blue", contain  : "3 light beige bags, 4 dark gray bags" },
{ name: "striped beige", contain  : "1 wavy coral bag, 5 light salmon bags, 5 dark black bags" },
{ name: "dull gold", contain  : "5 light gold bags, 4 bright silver bags" },
{ name: "wavy red", contain  : "4 bright gray bags, 1 striped green bag" },
{ name: "pale white", contain  : "2 plaid fuchsia bags, 3 shiny blue bags, 1 pale black bag, 3 dull purple bags" },
{ name: "bright orange", contain  : "5 dim bronze bags" },
{ name: "plaid yellow", contain  : "3 light beige bags" },
{ name: "clear red", contain  : "2 bright white bags, 5 light orange bags, 3 clear purple bags" },
{ name: "light tomato", contain  : "1 plaid fuchsia bag, 5 dark gray bags, 2 striped tan bags, 5 striped lavender bags" },
{ name: "pale yellow", contain  : "3 clear indigo bags" },
{ name: "shiny red", contain  : "5 bright violet bags, 2 striped cyan bags, 2 bright silver bags, 5 clear indigo bags" },
{ name: "bright maroon", contain  : "2 posh aqua bags, 1 plaid purple bag, 5 dull lavender bags, 4 faded turquoise bags" },
{ name: "dark crimson", contain  : "1 plaid chartreuse bag" },
{ name: "pale red", contain  : "1 faded lavender bag" },
{ name: "shiny lavender", contain  : "2 light orange bags" },
{ name: "dotted blue", contain  : "3 clear turquoise bags, 2 shiny silver bags" },
{ name: "bright lime", contain  : "5 mirrored plum bags, 2 dim blue bags, 4 light brown bags, 2 vibrant lavender bags" },
{ name: "bright lavender", contain  : "5 posh gray bags" },
{ name: "faded purple", contain  : "5 muted tan bags, 2 bright salmon bags, 2 shiny olive bags" },
{ name: "pale aqua", contain  : "4 clear black bags, 4 posh indigo bags" },
{ name: "wavy cyan", contain  : "5 faded green bags, 1 wavy lime bag" },
{ name: "dull maroon", contain  : "5 light indigo bags, 1 clear purple bag, 3 dark salmon bags" },
{ name: "muted fuchsia", contain  : "5 dotted silver bags, 4 plaid tomato bags, 2 drab olive bags, 4 vibrant tomato bags" },
{ name: "clear salmon", contain  : "3 faded tomato bags, 1 dull crimson bag" },
{ name: "drab maroon", contain  : "4 dotted blue bags, 1 dotted violet bag" },
{ name: "posh blue", contain  : "3 dotted bronze bags, 5 shiny chartreuse bags, 4 vibrant tan bags" },
{ name: "shiny gold", contain  : "1 plaid tan bag, 3 light beige bags, 1 posh brown bag" },
{ name: "light lavender", contain  : "3 posh maroon bags, 2 plaid beige bags, 1 dark gray bag, 5 muted bronze bags" },
{ name: "pale violet", contain  : "5 dull beige bags, 3 clear orange bags" },
{ name: "bright gold", contain  : "no other bags" },
{ name: "wavy maroon", contain  : "4 faded olive bags" },
{ name: "wavy salmon", contain  : "1 posh indigo bag, 1 clear fuchsia bag" },
{ name: "vibrant orange", contain  : "3 plaid tan bags, 4 dotted blue bags, 3 bright gold bags, 3 bright white bags" },
{ name: "vibrant green", contain  : "5 muted indigo bags, 4 muted aqua bags, 1 muted plum bag, 3 posh salmon bags" },
{ name: "striped tan", contain  : "1 plaid beige bag, 4 shiny bronze bags, 5 muted bronze bags, 4 clear indigo bags" },
{ name: "wavy silver", contain  : "4 muted fuchsia bags, 3 muted indigo bags, 1 vibrant cyan bag" },
{ name: "pale beige", contain  : "1 dim lavender bag, 1 clear lime bag, 4 faded lavender bags, 3 dull green bags" },
{ name: "mirrored brown", contain  : "1 plaid gray bag, 5 drab plum bags" },
{ name: "faded green", contain  : "5 light yellow bags, 2 plaid fuchsia bags, 1 drab magenta bag, 1 muted bronze bag" },
{ name: "posh red", contain  : "5 plaid magenta bags, 4 striped brown bags" },
{ name: "wavy turquoise", contain  : "2 posh coral bags, 3 faded violet bags, 4 striped green bags" },
{ name: "drab indigo", contain  : "2 mirrored red bags, 1 plaid blue bag" },
{ name: "shiny black", contain  : "3 clear crimson bags, 4 vibrant purple bags, 2 drab salmon bags" },
{ name: "wavy fuchsia", contain  : "4 wavy magenta bags, 5 plaid chartreuse bags, 4 posh salmon bags, 4 dull teal bags" },
{ name: "clear teal", contain  : "4 dark aqua bags" },
{ name: "posh tan", contain  : "2 clear silver bags, 1 faded coral bag" },
{ name: "plaid lime", contain  : "1 wavy lime bag" },
{ name: "vibrant tomato", contain  : "5 clear green bags, 3 posh olive bags, 5 mirrored beige bags" },
{ name: "dull crimson", contain  : "5 shiny blue bags, 5 dark magenta bags, 4 dim plum bags, 2 light lavender bags" },
{ name: "dotted salmon", contain  : "1 light maroon bag, 2 posh aqua bags, 2 light magenta bags" },
{ name: "striped orange", contain  : "no other bags" },
{ name: "vibrant bronze", contain  : "4 shiny black bags, 1 bright crimson bag" },
{ name: "posh black", contain  : "4 shiny turquoise bags, 2 muted indigo bags" },
{ name: "dim gray", contain  : "2 plaid purple bags, 3 bright blue bags, 2 plaid beige bags" },
{ name: "pale chartreuse", contain  : "5 dull beige bags" },
{ name: "wavy green", contain  : "2 drab tomato bags, 3 faded yellow bags, 5 posh aqua bags" },
{ name: "striped red", contain  : "3 posh green bags, 1 plaid red bag, 2 muted white bags, 4 dull teal bags" },
{ name: "muted black", contain  : "4 dark gray bags, 2 plaid fuchsia bags, 4 shiny purple bags, 2 wavy aqua bags" },
{ name: "vibrant gray", contain  : "5 drab bronze bags, 2 muted black bags, 2 clear lime bags" },
{ name: "dotted plum", contain  : "4 shiny silver bags, 3 light maroon bags, 4 bright white bags" },
{ name: "mirrored salmon", contain  : "2 plaid gold bags" },
{ name: "mirrored orange", contain  : "3 pale bronze bags" },
{ name: "dark gold", contain  : "3 light yellow bags" },
{ name: "muted orange", contain  : "5 dark black bags, 2 bright crimson bags, 1 posh bronze bag" },
{ name: "posh aqua", contain  : "3 plaid purple bags" },
{ name: "dotted lime", contain  : "3 shiny yellow bags, 4 dull brown bags, 2 dark gray bags" },
{ name: "drab lime", contain  : "3 wavy beige bags, 3 dull purple bags, 4 clear tan bags, 4 muted indigo bags" },
{ name: "bright blue", contain  : "5 plaid teal bags" },
{ name: "light orange", contain  : "2 plaid tan bags, 2 striped orange bags, 3 clear indigo bags" },
{ name: "dark chartreuse", contain  : "3 muted teal bags, 5 faded tomato bags" },
{ name: "clear gray", contain  : "5 bright bronze bags, 1 mirrored cyan bag" },
{ name: "vibrant lime", contain  : "4 striped green bags, 5 dotted lavender bags" },
{ name: "light black", contain  : "5 dark tan bags, 3 light magenta bags, 2 clear green bags, 4 dull lavender bags" },
{ name: "clear gold", contain  : "4 dotted bronze bags" },
{ name: "light aqua", contain  : "1 posh chartreuse bag, 4 mirrored silver bags, 1 dotted gray bag" },
{ name: "mirrored tan", contain  : "3 bright chartreuse bags, 5 dull olive bags, 2 bright white bags" },
{ name: "faded tomato", contain  : "3 faded coral bags, 3 wavy blue bags, 3 light lime bags" },
{ name: "drab chartreuse", contain  : "1 shiny red bag, 1 dotted violet bag" },
{ name: "striped tomato", contain  : "2 wavy yellow bags" },
{ name: "clear white", contain  : "2 drab bronze bags, 3 clear gray bags, 2 posh white bags" },
{ name: "shiny plum", contain  : "5 dim plum bags, 1 wavy beige bag, 1 faded fuchsia bag, 3 plaid white bags" },
{ name: "plaid violet", contain  : "3 posh coral bags, 5 dim gray bags, 3 dim plum bags, 3 dull purple bags" },
{ name: "dotted magenta", contain  : "4 dotted salmon bags" },
{ name: "mirrored cyan", contain  : "3 dark salmon bags, 5 muted teal bags, 2 faded white bags, 4 vibrant fuchsia bags" },
{ name: "muted teal", contain  : "2 faded violet bags, 4 dull cyan bags" },
{ name: "striped maroon", contain  : "1 mirrored olive bag" },
{ name: "mirrored turquoise", contain  : "3 plaid fuchsia bags, 3 mirrored cyan bags, 1 dull black bag" },
{ name: "shiny silver", contain  : "no other bags" },
{ name: "striped green", contain  : "1 wavy teal bag, 2 vibrant indigo bags, 2 dark lime bags" },
{ name: "striped silver", contain  : "4 bright yellow bags, 5 faded coral bags" },
{ name: "wavy olive", contain  : "4 posh gray bags, 5 dark cyan bags" },
{ name: "clear brown", contain  : "3 dull lavender bags, 4 dim gold bags" },
{ name: "bright turquoise", contain  : "3 faded lavender bags, 3 posh silver bags" },
{ name: "muted tan", contain  : "4 dim plum bags, 2 faded coral bags" },
{ name: "dull green", contain  : "1 shiny plum bag, 1 drab fuchsia bag, 5 dark white bags, 3 drab magenta bags" },
{ name: "drab yellow", contain  : "5 posh silver bags, 2 clear violet bags, 4 dull teal bags, 2 dotted salmon bags" },
{ name: "plaid aqua", contain  : "2 faded beige bags" },
{ name: "vibrant chartreuse", contain  : "2 wavy olive bags, 3 dotted salmon bags" },
{ name: "light chartreuse", contain  : "2 muted orange bags, 3 dotted black bags, 2 striped lavender bags, 4 striped red bags" },
{ name: "vibrant tan", contain  : "1 bright violet bag, 1 clear magenta bag, 4 dark orange bags" },
{ name: "posh turquoise", contain  : "5 bright gold bags, 3 striped violet bags" },
{ name: "dotted fuchsia", contain  : "5 faded lavender bags, 2 bright crimson bags, 5 muted yellow bags" },
{ name: "dark turquoise", contain  : "2 vibrant indigo bags, 5 dull tan bags" },
{ name: "dotted chartreuse", contain  : "5 pale red bags" },
{ name: "light lime", contain  : "4 bright gold bags, 5 shiny silver bags, 3 posh brown bags, 3 striped orange bags" },
{ name: "mirrored teal", contain  : "5 striped silver bags, 5 posh cyan bags, 4 light tomato bags, 4 dim gray bags" },
{ name: "vibrant turquoise", contain  : "2 drab plum bags, 4 dark blue bags, 2 dim violet bags, 2 plaid blue bags" },
{ name: "clear blue", contain  : "1 wavy indigo bag, 3 dotted yellow bags, 5 drab plum bags, 5 posh white bags" },
{ name: "striped blue", contain  : "1 wavy blue bag, 1 striped indigo bag, 4 dull black bags, 3 muted silver bags" },
{ name: "muted silver", contain  : "4 muted yellow bags, 1 plaid silver bag, 1 light lavender bag, 1 dotted blue bag" },
{ name: "dotted indigo", contain  : "5 clear tomato bags, 4 bright magenta bags, 5 dark crimson bags" },
{ name: "vibrant teal", contain  : "3 striped lavender bags, 4 wavy beige bags, 2 dull indigo bags" },
{ name: "striped chartreuse", contain  : "5 clear silver bags, 3 drab yellow bags, 5 striped indigo bags, 1 faded turquoise bag" },
{ name: "dotted violet", contain  : "5 dark plum bags, 5 dark white bags" },
{ name: "light brown", contain  : "3 faded tomato bags, 5 dark bronze bags, 3 shiny turquoise bags, 2 striped violet bags" },
{ name: "posh indigo", contain  : "2 vibrant coral bags, 2 wavy maroon bags, 4 drab coral bags, 2 clear fuchsia bags" },
{ name: "drab violet", contain  : "5 drab tomato bags, 1 light silver bag, 5 wavy beige bags" },
{ name: "plaid plum", contain  : "1 dull magenta bag, 3 dark black bags" },
{ name: "dotted orange", contain  : "5 mirrored crimson bags" },
{ name: "dotted teal", contain  : "3 clear silver bags" },
{ name: "vibrant brown", contain  : "5 vibrant indigo bags" },
{ name: "clear orange", contain  : "1 clear turquoise bag" },
{ name: "bright magenta", contain  : "1 dark orange bag, 2 dotted purple bags, 1 mirrored white bag, 5 vibrant yellow bags" },
{ name: "clear tan", contain  : "2 striped orange bags" },
{ name: "dotted brown", contain  : "2 mirrored coral bags, 4 wavy magenta bags, 2 pale purple bags, 1 drab black bag" },
{ name: "vibrant plum", contain  : "1 dotted teal bag" },
{ name: "light indigo", contain  : "5 light black bags, 1 vibrant purple bag, 3 muted olive bags, 4 mirrored brown bags" },
{ name: "bright chartreuse", contain  : "3 dull lime bags" },
{ name: "clear turquoise", contain  : "4 pale black bags, 5 plaid purple bags, 4 bright gold bags" },
{ name: "dim crimson", contain  : "3 wavy lime bags" },
{ name: "pale tan", contain  : "3 mirrored white bags, 3 drab bronze bags, 2 drab black bags" },
{ name: "plaid gold", contain  : "5 striped orange bags" },
{ name: "striped crimson", contain  : "1 muted brown bag, 4 drab red bags, 1 faded crimson bag" },
{ name: "clear lavender", contain  : "1 bright salmon bag, 2 clear teal bags, 4 drab plum bags" },
{ name: "dark maroon", contain  : "2 striped purple bags, 1 bright aqua bag, 3 faded white bags, 5 bright yellow bags" },
{ name: "drab gray", contain  : "5 posh silver bags, 2 bright chartreuse bags, 2 dim purple bags, 5 faded brown bags" },
{ name: "faded olive", contain  : "2 shiny turquoise bags, 5 drab green bags, 4 light maroon bags" },
{ name: "muted gray", contain  : "2 dim maroon bags, 5 muted tan bags, 3 faded salmon bags, 5 faded white bags" },
{ name: "posh violet", contain  : "2 faded crimson bags" },
{ name: "shiny white", contain  : "1 dark chartreuse bag, 5 posh green bags" },
{ name: "mirrored indigo", contain  : "5 clear purple bags, 3 dark turquoise bags, 3 clear aqua bags, 2 bright gray bags" },
{ name: "dark brown", contain  : "4 wavy gold bags" },
{ name: "muted tomato", contain  : "4 clear violet bags" },
{ name: "striped black", contain  : "4 plaid white bags, 3 dull tan bags" },
{ name: "shiny crimson", contain  : "2 plaid teal bags" },
{ name: "bright coral", contain  : "2 clear plum bags, 2 faded orange bags, 3 mirrored silver bags" },
{ name: "dark yellow", contain  : "1 plaid olive bag, 3 dotted white bags" },
{ name: "faded beige", contain  : "5 posh aqua bags, 1 pale purple bag" },
{ name: "wavy magenta", contain  : "3 dull yellow bags, 5 faded cyan bags" },
{ name: "wavy bronze", contain  : "5 dull lime bags" },
{ name: "dim lavender", contain  : "3 plaid red bags, 3 bright brown bags" },
{ name: "dim indigo", contain  : "3 dim violet bags, 4 bright silver bags" },
{ name: "posh green", contain  : "4 drab white bags, 3 plaid tan bags, 1 light orange bag" },
{ name: "pale gray", contain  : "1 muted indigo bag, 2 dotted fuchsia bags" },
{ name: "mirrored gold", contain  : "2 striped beige bags, 3 bright plum bags" },
{ name: "striped white", contain  : "5 dark blue bags, 5 dotted purple bags, 4 clear maroon bags" },
{ name: "drab cyan", contain  : "3 dotted white bags" },
{ name: "vibrant aqua", contain  : "4 posh yellow bags, 1 drab tomato bag" },
{ name: "light gold", contain  : "2 vibrant purple bags, 5 light black bags" },
{ name: "dotted yellow", contain  : "5 striped lavender bags, 2 posh aqua bags, 2 clear green bags, 2 dull green bags" },
{ name: "vibrant cyan", contain  : "2 dark gray bags, 2 dark lavender bags, 1 striped red bag, 2 striped indigo bags" },
{ name: "posh yellow", contain  : "3 wavy olive bags, 2 bright gray bags, 2 posh gray bags, 2 vibrant white bags" },
{ name: "faded salmon", contain  : "4 plaid beige bags, 1 drab teal bag" },
{ name: "bright purple", contain  : "1 faded white bag, 3 plaid teal bags, 3 light lime bags, 1 pale purple bag" },
{ name: "dotted purple", contain  : "3 mirrored salmon bags, 3 drab olive bags" },
{ name: "plaid red", contain  : "5 faded violet bags, 5 dotted white bags" },
{ name: "vibrant maroon", contain  : "3 faded green bags, 3 bright chartreuse bags, 4 clear orange bags, 2 dim tomato bags" },
{ name: "clear crimson", contain  : "1 vibrant purple bag, 5 light beige bags, 5 vibrant olive bags" },
{ name: "clear cyan", contain  : "1 posh plum bag, 2 vibrant chartreuse bags, 5 plaid silver bags" },
{ name: "vibrant salmon", contain  : "2 striped brown bags" },
{ name: "striped olive", contain  : "2 muted indigo bags" },
{ name: "dim turquoise", contain  : "3 striped violet bags, 1 wavy blue bag" },
{ name: "bright brown", contain  : "1 shiny yellow bag" },
{ name: "mirrored tomato", contain  : "1 bright violet bag, 1 faded green bag, 3 dotted gray bags, 3 muted silver bags" },
{ name: "dark green", contain  : "1 dull olive bag" },
{ name: "wavy white", contain  : "4 bright silver bags, 5 vibrant tomato bags, 2 vibrant salmon bags, 4 clear tomato bags" },
{ name: "shiny green", contain  : "1 dotted white bag" },
{ name: "dotted aqua", contain  : "1 faded lavender bag, 1 pale coral bag, 1 clear silver bag" },
{ name: "shiny aqua", contain  : "1 plaid white bag, 4 clear lime bags" },
{ name: "dark lavender", contain  : "3 bright aqua bags, 3 mirrored salmon bags, 5 pale red bags, 1 pale purple bag" },
{ name: "dull violet", contain  : "5 wavy gold bags, 1 shiny cyan bag, 5 plaid beige bags" },
{ name: "drab tan", contain  : "2 drab crimson bags, 1 drab cyan bag, 5 striped tan bags, 3 dotted fuchsia bags" },
{ name: "plaid turquoise", contain  : "1 posh silver bag, 4 posh turquoise bags, 5 posh tan bags" },
{ name: "pale lavender", contain  : "3 plaid gold bags, 5 pale gray bags, 4 dotted plum bags, 3 mirrored crimson bags" },
{ name: "clear indigo", contain  : "5 pale purple bags" },
{ name: "wavy purple", contain  : "3 bright yellow bags, 1 wavy gold bag, 3 light lavender bags" },
{ name: "shiny salmon", contain  : "3 light orange bags" },
{ name: "mirrored crimson", contain  : "4 dull salmon bags, 4 light yellow bags, 3 dark gray bags, 4 dotted blue bags" },
{ name: "plaid chartreuse", contain  : "2 shiny turquoise bags" },
{ name: "pale orange", contain  : "2 muted lavender bags" },
{ name: "dark cyan", contain  : "5 bright lavender bags, 3 wavy black bags, 2 shiny plum bags, 3 dim aqua bags" },
{ name: "dim brown", contain  : "1 shiny yellow bag, 2 posh plum bags, 3 muted black bags, 4 light white bags" },
{ name: "pale blue", contain  : "1 faded cyan bag, 3 faded crimson bags, 1 wavy indigo bag, 3 dark plum bags" },
{ name: "vibrant red", contain  : "5 plaid aqua bags, 2 clear fuchsia bags" },
{ name: "dark salmon", contain  : "4 striped violet bags" },
{ name: "bright black", contain  : "1 faded silver bag" },
{ name: "vibrant white", contain  : "2 vibrant yellow bags, 3 shiny plum bags" },
{ name: "muted violet", contain  : "4 pale lavender bags, 4 pale purple bags" },
{ name: "wavy coral", contain  : "5 vibrant tomato bags" },
{ name: "striped salmon", contain  : "3 dull magenta bags" },
{ name: "faded blue", contain  : "2 bright salmon bags, 2 clear salmon bags, 4 striped indigo bags" },
{ name: "dim violet", contain  : "1 striped brown bag, 5 bright blue bags, 4 bright bronze bags, 5 dull salmon bags" },
{ name: "faded chartreuse", contain  : "2 muted tan bags, 1 plaid aqua bag, 4 dotted white bags" },
{ name: "posh silver", contain  : "4 dull salmon bags" },
{ name: "dim red", contain  : "1 faded black bag, 2 dark aqua bags, 2 drab crimson bags, 5 dotted aqua bags" },
{ name: "dull lime", contain  : "3 pale indigo bags, 5 bright gold bags, 5 light orange bags" },
{ name: "striped fuchsia", contain  : "3 clear violet bags, 2 light fuchsia bags, 1 plaid red bag, 3 wavy aqua bags" },
{ name: "vibrant lavender", contain  : "1 dark teal bag, 1 dark beige bag, 4 dark cyan bags" },
{ name: "dark gray", contain  : "5 drab magenta bags, 3 muted bronze bags, 5 posh gray bags, 2 shiny silver bags" },
{ name: "drab lavender", contain  : "4 pale indigo bags, 4 bright salmon bags, 3 posh aqua bags, 4 bright lavender bags" },
{ name: "mirrored white", contain  : "3 striped black bags" },
{ name: "bright aqua", contain  : "4 plaid tomato bags, 3 clear fuchsia bags, 1 light silver bag" },
{ name: "dark silver", contain  : "3 bright tomato bags" },
{ name: "drab fuchsia", contain  : "5 dotted plum bags, 2 posh aqua bags, 2 clear red bags, 1 dark gray bag" },
{ name: "bright teal", contain  : "3 vibrant tan bags" },
{ name: "striped indigo", contain  : "5 wavy plum bags, 2 wavy lavender bags, 4 mirrored beige bags, 4 clear green bags" },
{ name: "dark white", contain  : "4 striped brown bags, 4 plaid teal bags, 2 posh brown bags, 2 wavy blue bags" },
{ name: "mirrored maroon", contain  : "2 clear cyan bags, 4 shiny aqua bags" },
{ name: "wavy tan", contain  : "5 bright maroon bags, 1 clear teal bag" },
{ name: "wavy lime", contain  : "3 pale purple bags, 5 plaid teal bags, 5 bright gold bags, 3 clear turquoise bags" },
{ name: "dark plum", contain  : "1 dotted orange bag" },
{ name: "posh cyan", contain  : "1 light lavender bag, 1 dark orange bag, 2 dull lime bags" },
{ name: "pale crimson", contain  : "3 faded fuchsia bags, 4 drab orange bags" },
{ name: "clear yellow", contain  : "4 posh tan bags" },
{ name: "striped yellow", contain  : "2 muted red bags, 1 light silver bag, 5 mirrored chartreuse bags" },
{ name: "clear silver", contain  : "2 dull lavender bags, 3 faded fuchsia bags" },
{ name: "drab red", contain  : "3 clear orange bags" },
{ name: "dotted turquoise", contain  : "4 bright lavender bags" },
{ name: "striped purple", contain  : "1 shiny plum bag, 2 clear orange bags, 3 mirrored turquoise bags, 3 striped orange bags" },
{ name: "striped gray", contain  : "1 posh silver bag" },
{ name: "clear purple", contain  : "4 muted bronze bags, 3 shiny silver bags, 4 pale salmon bags, 3 plaid fuchsia bags" },
{ name: "light gray", contain  : "5 dark fuchsia bags" },
{ name: "dull tan", contain  : "1 plaid fuchsia bag" },
{ name: "muted blue", contain  : "5 dark plum bags, 4 wavy chartreuse bags, 2 drab green bags" },
{ name: "dull brown", contain  : "1 pale gold bag" },
{ name: "bright fuchsia", contain  : "1 pale bronze bag, 2 bright yellow bags, 4 drab gold bags" },
{ name: "plaid purple", contain  : "no other bags" },
{ name: "drab silver", contain  : "3 wavy blue bags, 2 wavy black bags, 2 dark olive bags" },
{ name: "light salmon", contain  : "5 wavy plum bags, 4 drab white bags, 5 muted bronze bags, 5 mirrored beige bags" },
{ name: "drab beige", contain  : "2 bright silver bags, 1 striped blue bag, 2 wavy white bags, 1 plaid lavender bag" },
{ name: "posh beige", contain  : "3 dotted tomato bags, 5 wavy chartreuse bags" },
{ name: "muted cyan", contain  : "4 dim bronze bags, 5 muted white bags, 3 pale black bags, 2 shiny silver bags" },
{ name: "dull magenta", contain  : "1 posh white bag" },
{ name: "shiny cyan", contain  : "1 shiny silver bag, 4 pale salmon bags, 5 faded turquoise bags" },
{ name: "mirrored gray", contain  : "4 mirrored red bags, 3 vibrant brown bags" },
{ name: "bright cyan", contain  : "1 dotted lavender bag" },
{ name: "dotted crimson", contain  : "3 wavy yellow bags, 1 shiny brown bag, 2 striped brown bags, 2 dull yellow bags" },
{ name: "dim chartreuse", contain  : "5 shiny purple bags" },
{ name: "muted crimson", contain  : "2 striped violet bags, 4 clear tan bags" },
{ name: "dim aqua", contain  : "1 mirrored magenta bag, 3 dim beige bags" },
{ name: "wavy aqua", contain  : "4 bright gray bags" },
{ name: "bright beige", contain  : "4 dotted chartreuse bags" },
{ name: "posh purple", contain  : "5 wavy aqua bags, 4 posh coral bags, 3 vibrant chartreuse bags" },
{ name: "shiny fuchsia", contain  : "1 shiny olive bag" },
{ name: "wavy beige", contain  : "2 pale purple bags, 3 pale indigo bags, 3 plaid purple bags" },
{ name: "wavy crimson", contain  : "4 shiny gold bags, 5 bright tomato bags" },
{ name: "pale tomato", contain  : "3 faded gold bags, 5 shiny gray bags" },
{ name: "bright silver", contain  : "1 dotted white bag" },
{ name: "mirrored chartreuse", contain  : "2 muted silver bags" },
{ name: "mirrored aqua", contain  : "4 plaid violet bags" },
{ name: "wavy brown", contain  : "4 faded beige bags, 4 faded brown bags, 2 mirrored blue bags, 3 clear red bags" },
{ name: "dull purple", contain  : "3 plaid fuchsia bags, 1 faded lavender bag" },
{ name: "pale turquoise", contain  : "4 mirrored violet bags, 3 faded salmon bags, 5 bright white bags" },
{ name: "dull lavender", contain  : "1 faded fuchsia bag" },
{ name: "dull aqua", contain  : "1 bright yellow bag" },
{ name: "clear maroon", contain  : "1 pale bronze bag, 2 clear aqua bags" },
{ name: "wavy lavender", contain  : "4 dotted blue bags" },
{ name: "dull blue", contain  : "5 wavy magenta bags" },
{ name: "shiny olive", contain  : "4 clear magenta bags, 1 vibrant orange bag" },
{ name: "shiny teal", contain  : "5 dotted magenta bags, 2 dark crimson bags, 3 dotted brown bags" },
{ name: "dull teal", contain  : "1 dull indigo bag, 4 wavy plum bags, 2 drab plum bags" },
{ name: "dim bronze", contain  : "5 striped silver bags, 5 posh green bags" },
{ name: "muted bronze", contain  : "4 dotted blue bags, 3 pale purple bags, 5 drab magenta bags" },
{ name: "vibrant violet", contain  : "3 dim tan bags, 3 striped lavender bags" },
{ name: "dull turquoise", contain  : "1 dim white bag" },
{ name: "pale purple", contain  : "no other bags" },
{ name: "drab aqua", contain  : "4 dull beige bags, 5 clear brown bags, 2 mirrored orange bags, 3 mirrored blue bags" },
{ name: "mirrored beige", contain  : "4 posh aqua bags" },
{ name: "pale plum", contain  : "4 dull coral bags, 4 pale black bags, 1 posh chartreuse bag" },
{ name: "dotted maroon", contain  : "5 faded gold bags, 1 clear blue bag, 4 dark black bags" },
{ name: "muted olive", contain  : "5 dim violet bags, 4 dotted white bags, 5 plaid purple bags, 3 vibrant orange bags" },
{ name: "wavy yellow", contain  : "4 light beige bags" },
{ name: "plaid salmon", contain  : "4 pale black bags, 3 dim bronze bags, 1 dotted gold bag" },
{ name: "faded indigo", contain  : "3 plaid purple bags, 5 pale gold bags, 1 wavy beige bag" },
{ name: "pale brown", contain  : "2 wavy black bags" },
{ name: "clear olive", contain  : "4 vibrant tomato bags" },
{ name: "vibrant gold", contain  : "3 dull cyan bags" },
{ name: "dark indigo", contain  : "5 bright green bags, 1 dark white bag" },
{ name: "drab gold", contain  : "4 clear violet bags, 2 striped indigo bags" },
{ name: "light bronze", contain  : "3 shiny coral bags" },
{ name: "vibrant black", contain  : "2 light black bags, 5 clear orange bags, 2 clear silver bags" },
{ name: "wavy tomato", contain  : "1 faded maroon bag, 1 dim violet bag, 5 posh aqua bags" },
{ name: "wavy orange", contain  : "2 striped lime bags, 4 posh turquoise bags, 3 dotted purple bags, 1 wavy gold bag" },
{ name: "dark blue", contain  : "1 faded gray bag" },
{ name: "drab magenta", contain  : "no other bags" },
{ name: "posh crimson", contain  : "1 mirrored olive bag, 1 striped tomato bag, 5 vibrant orange bags, 1 drab yellow bag" },
{ name: "mirrored coral", contain  : "4 drab purple bags, 4 bright gray bags, 4 plaid turquoise bags, 5 plaid aqua bags" },
{ name: "faded crimson", contain  : "3 plaid tan bags, 3 vibrant orange bags, 3 mirrored beige bags, 4 dim plum bags" },
{ name: "dotted tan", contain  : "1 wavy beige bag, 2 bright maroon bags" },
{ name: "faded magenta", contain  : "1 mirrored tan bag" },
{ name: "light maroon", contain  : "4 plaid tan bags, 5 shiny silver bags" },
{ name: "dull chartreuse", contain  : "2 dim gold bags, 1 faded blue bag, 1 striped violet bag, 4 drab tomato bags" },
{ name: "plaid white", contain  : "2 dark gray bags" },
{ name: "plaid fuchsia", contain  : "no other bags" },
{ name: "dark red", contain  : "2 mirrored bronze bags, 2 pale blue bags, 5 plaid orange bags, 5 clear orange bags" },
{ name: "dark fuchsia", contain  : "2 faded green bags, 2 mirrored magenta bags, 3 pale red bags" },
{ name: "dull plum", contain  : "2 bright blue bags, 3 drab purple bags, 1 dim plum bag, 2 shiny purple bags" },
{ name: "vibrant crimson", contain  : "2 bright plum bags" },
{ name: "clear magenta", contain  : "1 drab bronze bag, 2 bright turquoise bags, 2 faded gray bags, 1 dim blue bag" },
{ name: "dull indigo", contain  : "5 light magenta bags" },
{ name: "vibrant olive", contain  : "3 light yellow bags, 3 mirrored silver bags, 2 plaid white bags, 2 dim beige bags" },
{ name: "striped lavender", contain  : "1 dull salmon bag, 1 pale purple bag" },
{ name: "clear lime", contain  : "4 dim gold bags" },
{ name: "faded orange", contain  : "5 light white bags, 4 shiny bronze bags, 3 plaid silver bags" },
{ name: "posh lime", contain  : "2 drab orange bags, 5 wavy beige bags" },
{ name: "posh olive", contain  : "5 drab green bags, 2 bright maroon bags, 3 vibrant orange bags" },
{ name: "dim yellow", contain  : "1 light silver bag, 5 vibrant gray bags, 4 faded turquoise bags, 2 dark blue bags" },
{ name: "muted red", contain  : "2 dim purple bags" },
{ name: "pale salmon", contain  : "3 vibrant orange bags" },
{ name: "light beige", contain  : "5 clear purple bags, 2 plaid teal bags" },
{ name: "clear tomato", contain  : "5 dull cyan bags, 4 dark brown bags" },
{ name: "shiny gray", contain  : "3 dark brown bags, 1 shiny bronze bag, 5 posh bronze bags, 4 dark indigo bags" },
{ name: "vibrant fuchsia", contain  : "4 wavy olive bags, 5 shiny blue bags, 5 light yellow bags" },
{ name: "shiny violet", contain  : "4 dull aqua bags, 1 pale fuchsia bag, 3 mirrored lime bags, 5 dark blue bags" },
{ name: "plaid silver", contain  : "1 faded fuchsia bag, 5 dull lavender bags" },
{ name: "light white", contain  : "1 plaid magenta bag, 4 striped beige bags" },
{ name: "posh magenta", contain  : "5 vibrant chartreuse bags, 3 drab silver bags, 4 striped bronze bags, 4 striped salmon bags" },
{ name: "muted maroon", contain  : "2 faded coral bags" },
{ name: "light blue", contain  : "3 dotted plum bags, 2 pale salmon bags, 4 striped coral bags, 1 bright lavender bag" },
{ name: "pale teal", contain  : "3 faded maroon bags, 5 wavy turquoise bags" },
{ name: "posh gold", contain  : "4 vibrant violet bags, 1 drab beige bag" },
{ name: "shiny indigo", contain  : "4 drab cyan bags" },
{ name: "wavy teal", contain  : "1 light maroon bag, 2 shiny silver bags, 2 bright white bags, 1 pale black bag" },
{ name: "striped cyan", contain  : "1 plaid brown bag" },
{ name: "pale black", contain  : "no other bags" },
{ name: "light green", contain  : "2 dark salmon bags, 2 faded tomato bags, 1 wavy blue bag, 1 bright gray bag" },
{ name: "mirrored green", contain  : "2 striped salmon bags, 3 shiny black bags" },
{ name: "dim orange", contain  : "3 vibrant plum bags, 5 drab crimson bags" },
{ name: "clear chartreuse", contain  : "2 posh fuchsia bags, 3 vibrant olive bags" },
{ name: "dull black", contain  : "3 posh yellow bags, 5 dark bronze bags, 4 dark aqua bags, 5 dull teal bags" },
{ name: "dotted tomato", contain  : "2 faded crimson bags, 5 faded black bags" },
{ name: "faded maroon", contain  : "4 pale white bags, 5 posh green bags, 3 wavy black bags, 5 plaid tan bags" },
{ name: "plaid cyan", contain  : "3 striped blue bags, 3 wavy teal bags" },
{ name: "dark bronze", contain  : "2 clear purple bags" },
{ name: "vibrant purple", contain  : "2 striped orange bags, 1 wavy black bag" },
{ name: "dotted silver", contain  : "4 faded white bags, 5 dim blue bags, 1 dark white bag" },
{ name: "mirrored yellow", contain  : "5 dark black bags" },
{ name: "dim lime", contain  : "3 dim lavender bags, 5 shiny gold bags, 5 striped red bags" },
{ name: "faded tan", contain  : "4 clear black bags, 3 pale silver bags, 1 muted gold bag" },
{ name: "drab plum", contain  : "4 shiny gold bags" },
{ name: "plaid lavender", contain  : "3 drab blue bags, 3 faded tomato bags, 5 bright cyan bags" },
{ name: "dark beige", contain  : "3 dim indigo bags, 2 plaid white bags" },
{ name: "dotted red", contain  : "2 mirrored indigo bags" },
{ name: "dull orange", contain  : "3 mirrored cyan bags, 4 shiny gold bags, 5 posh white bags" },
{ name: "striped bronze", contain  : "1 drab coral bag, 1 dark teal bag, 5 posh yellow bags" },
{ name: "wavy indigo", contain  : "1 drab lavender bag, 2 posh aqua bags, 1 clear brown bag" },
{ name: "light cyan", contain  : "3 dim blue bags, 5 dark brown bags, 3 clear bronze bags" },
{ name: "plaid orange", contain  : "4 plaid tan bags, 1 posh tomato bag, 1 wavy crimson bag" },
{ name: "faded turquoise", contain  : "1 muted bronze bag, 1 wavy gold bag, 4 striped orange bags, 3 bright gold bags" },
{ name: "shiny orange", contain  : "1 wavy maroon bag" },
{ name: "light tan", contain  : "5 mirrored black bags, 4 dark tan bags" },
{ name: "pale coral", contain  : "1 faded coral bag, 4 dotted yellow bags" },
{ name: "faded lavender", contain  : "3 vibrant orange bags, 4 pale black bags, 2 posh aqua bags, 5 shiny gold bags" },
{ name: "dull cyan", contain  : "3 bright maroon bags, 4 light yellow bags, 4 faded tomato bags" },
{ name: "shiny turquoise", contain  : "1 posh gray bag" },
{ name: "faded violet", contain  : "5 posh tan bags, 3 dim blue bags" },
{ name: "mirrored bronze", contain  : "1 striped silver bag" },
{ name: "dull tomato", contain  : "1 dim black bag, 5 wavy olive bags, 1 faded olive bag" },
{ name: "faded red", contain  : "2 drab salmon bags, 2 posh aqua bags, 5 posh brown bags" },
{ name: "dark magenta", contain  : "1 posh silver bag, 5 bright lavender bags, 4 faded turquoise bags, 5 drab white bags" },
{ name: "light turquoise", contain  : "5 dotted turquoise bags, 2 dim plum bags, 2 posh olive bags, 4 mirrored gold bags" },
{ name: "clear green", contain  : "3 bright white bags, 2 dark tan bags" },
{ name: "clear coral", contain  : "3 clear turquoise bags, 2 striped black bags" },
{ name: "dotted bronze", contain  : "5 striped blue bags, 2 striped lavender bags, 4 bright salmon bags, 5 drab maroon bags" },
{ name: "drab salmon", contain  : "3 bright blue bags, 4 drab magenta bags" },
{ name: "faded aqua", contain  : "2 light magenta bags" },
{ name: "bright violet", contain  : "2 wavy indigo bags" },
{ name: "mirrored silver", contain  : "5 shiny gold bags" },
{ name: "posh maroon", contain  : "1 dark lime bag, 4 plaid gold bags, 4 light magenta bags, 4 dim aqua bags" },
{ name: "striped brown", contain  : "5 dull lavender bags" },
{ name: "bright olive", contain  : "3 striped coral bags" },
{ name: "drab white", contain  : "5 plaid teal bags, 3 shiny silver bags, 3 wavy plum bags, 1 bright white bag" },
{ name: "faded teal", contain  : "3 muted blue bags, 2 bright purple bags" },
{ name: "striped plum", contain  : "4 plaid turquoise bags, 5 vibrant fuchsia bags" },
{ name: "dark coral", contain  : "1 muted salmon bag, 1 mirrored bronze bag, 3 pale maroon bags, 5 dotted coral bags" },
{ name: "drab orange", contain  : "1 pale gold bag" },
{ name: "bright tan", contain  : "3 pale plum bags, 2 posh yellow bags" },
{ name: "drab brown", contain  : "1 plaid red bag, 4 pale tan bags" },
{ name: "posh bronze", contain  : "4 dim indigo bags, 4 drab purple bags, 2 dark bronze bags" },
{ name: "mirrored purple", contain  : "3 plaid beige bags, 3 bright tomato bags, 3 bright chartreuse bags, 4 wavy crimson bags" },
{ name: "wavy blue", contain  : "1 dotted blue bag, 1 pale purple bag, 3 light maroon bags" },
{ name: "dim cyan", contain  : "5 faded yellow bags, 2 shiny coral bags, 3 faded black bags, 4 vibrant chartreuse bags" },
{ name: "plaid olive", contain  : "1 dim aqua bag, 4 mirrored indigo bags, 4 muted silver bags" },
{ name: "dark orange", contain  : "5 faded fuchsia bags, 4 clear purple bags" },
{ name: "drab olive", contain  : "1 drab lavender bag" },
{ name: "pale fuchsia", contain  : "3 bright green bags, 4 striped red bags, 2 pale brown bags" },
{ name: "shiny chartreuse", contain  : "2 striped beige bags, 3 clear tomato bags" },
{ name: "shiny brown", contain  : "1 faded maroon bag, 2 muted brown bags, 2 vibrant coral bags" },
{ name: "striped turquoise", contain  : "4 pale bronze bags" },
{ name: "dull gray", contain  : "4 plaid gray bags" },
{ name: "wavy chartreuse", contain  : "2 wavy maroon bags, 4 muted yellow bags" },
{ name: "bright green", contain  : "2 dotted orange bags, 4 faded olive bags, 5 wavy beige bags, 1 bright yellow bag" },
{ name: "dark olive", contain  : "5 light indigo bags, 5 plaid chartreuse bags, 2 vibrant red bags, 5 dark lime bags" },
{ name: "dark black", contain  : "2 dark fuchsia bags, 1 dotted fuchsia bag" },
{ name: "dim purple", contain  : "5 posh gray bags, 3 faded lavender bags, 4 bright plum bags, 2 dotted salmon bags" },
{ name: "pale gold", contain  : "1 posh silver bag, 4 posh tan bags, 1 bright gold bag, 5 faded gray bags" },
{ name: "pale maroon", contain  : "2 drab fuchsia bags, 2 dark fuchsia bags, 5 plaid red bags" },
{ name: "light plum", contain  : "1 dim beige bag, 2 light orange bags" },
{ name: "mirrored plum", contain  : "5 light white bags, 5 bright tomato bags, 1 dim violet bag" },
{ name: "dim coral", contain  : "2 light lime bags, 2 clear tan bags" },
{ name: "faded silver", contain  : "4 striped violet bags, 2 mirrored brown bags" },
{ name: "posh salmon", contain  : "4 dull plum bags" },
{ name: "shiny purple", contain  : "2 posh gray bags" },
{ name: "shiny maroon", contain  : "2 vibrant turquoise bags, 4 drab teal bags" },
{ name: "clear beige", contain  : "2 mirrored white bags, 1 shiny turquoise bag, 5 faded bronze bags" },
{ name: "muted plum", contain  : "2 plaid violet bags" },
{ name: "plaid green", contain  : "3 drab white bags, 5 wavy gold bags, 3 bright maroon bags, 1 wavy cyan bag" },
{ name: "faded white", contain  : "1 dull cyan bag, 3 dull purple bags, 2 bright brown bags, 4 bright crimson bags" },
{ name: "plaid gray", contain  : "3 bright chartreuse bags, 2 plaid tomato bags, 2 dark brown bags" },
{ name: "shiny yellow", contain  : "5 drab salmon bags" },
{ name: "mirrored violet", contain  : "4 clear fuchsia bags" },
{ name: "plaid beige", contain  : "1 pale black bag" },
{ name: "plaid black", contain  : "1 dark chartreuse bag" },
{ name: "mirrored fuchsia", contain  : "5 light tomato bags, 4 shiny yellow bags, 1 plaid beige bag, 5 muted gold bags" },
{ name: "pale indigo", contain  : "1 pale black bag, 5 plaid teal bags" },
{ name: "light magenta", contain  : "1 mirrored silver bag, 4 dull salmon bags" },
{ name: "striped teal", contain  : "1 dotted lime bag, 3 shiny yellow bags, 3 wavy aqua bags" },
{ name: "dark aqua", contain  : "3 drab green bags" },
{ name: "bright red", contain  : "5 shiny chartreuse bags, 3 mirrored bronze bags, 1 pale beige bag" },
{ name: "dim teal", contain  : "2 shiny yellow bags, 3 drab turquoise bags, 1 striped black bag, 1 vibrant coral bag" },
{ name: "drab crimson", contain  : "5 light silver bags, 4 plaid chartreuse bags" },
{ name: "dim silver", contain  : "1 striped brown bag, 5 dark black bags, 1 light lime bag" },
{ name: "drab bronze", contain  : "1 dotted white bag" },
{ name: "drab teal", contain  : "2 dim blue bags, 4 light yellow bags, 5 dark gray bags" },
{ name: "dark teal", contain  : "5 posh gray bags, 4 faded green bags, 1 dotted yellow bag, 4 vibrant black bags" },
{ name: "vibrant indigo", contain  : "4 faded turquoise bags" },
{ name: "mirrored black", contain  : "2 muted bronze bags" },
{ name: "dotted gray", contain  : "3 faded cyan bags" },
{ name: "posh plum", contain  : "4 dark bronze bags, 3 drab olive bags, 4 dull beige bags, 3 plaid silver bags" },
{ name: "drab black", contain  : "1 wavy teal bag" },
{ name: "faded gray", contain  : "5 dull lime bags, 4 posh aqua bags" },
{ name: "muted white", contain  : "2 shiny lavender bags, 3 wavy olive bags, 4 bright brown bags" },
{ name: "wavy gray", contain  : "3 faded lavender bags, 5 posh silver bags" },
{ name: "plaid magenta", contain  : "1 shiny silver bag, 3 light silver bags, 5 posh gray bags, 2 faded green bags" },
{ name: "muted coral", contain  : "5 dull salmon bags, 4 shiny plum bags" },
{ name: "plaid tomato", contain  : "5 dotted blue bags" },
{ name: "dark lime", contain  : "1 striped orange bag, 1 pale black bag" },
{ name: "vibrant coral", contain  : "1 vibrant yellow bag, 1 plaid magenta bag, 3 pale gray bags, 2 vibrant indigo bags" },
{ name: "drab turquoise", contain  : "2 plaid tomato bags, 3 dim indigo bags, 2 shiny tomato bags, 1 plaid red bag" },
{ name: "mirrored red", contain  : "5 plaid chartreuse bags" },
{ name: "plaid brown", contain  : "5 drab blue bags, 1 mirrored olive bag" },
{ name: "striped gold", contain  : "3 vibrant aqua bags, 1 posh plum bag, 1 dotted blue bag, 3 light yellow bags" },
{ name: "drab purple", contain  : "2 clear green bags, 4 dull cyan bags, 3 posh tan bags, 5 faded violet bags" },
{ name: "posh chartreuse", contain  : "2 pale black bags" },
{ name: "clear violet", contain  : "1 dark tomato bag, 4 light lime bags, 4 faded magenta bags" },
{ name: "striped magenta", contain  : "5 wavy plum bags, 2 light maroon bags, 4 posh gray bags, 2 shiny silver bags" },
{ name: "muted salmon", contain  : "5 muted black bags, 5 vibrant coral bags" },
{ name: "pale silver", contain  : "3 light lime bags, 3 dotted orange bags, 4 plaid teal bags" },
{ name: "striped lime", contain  : "5 dim tomato bags, 2 clear purple bags, 2 mirrored brown bags" },
{ name: "dull silver", contain  : "2 wavy gold bags" },
{ name: "dark violet", contain  : "1 dotted plum bag, 5 faded turquoise bags, 4 light salmon bags" },
{ name: "dim black", contain  : "4 clear violet bags, 4 posh chartreuse bags, 1 plaid turquoise bag, 1 pale black bag" },
{ name: "shiny beige", contain  : "3 dim aqua bags" },
{ name: "plaid tan", contain  : "no other bags" },
{ name: "faded yellow", contain  : "5 vibrant fuchsia bags" },
{ name: "vibrant blue", contain  : "2 vibrant olive bags, 4 faded cyan bags" },
{ name: "mirrored lime", contain  : "3 mirrored blue bags" },
{ name: "dull white", contain  : "5 dark brown bags" },
{ name: "dim tomato", contain  : "4 dark violet bags, 5 dotted tan bags, 1 plaid teal bag, 2 shiny plum bags" },
{ name: "pale cyan", contain  : "1 dotted coral bag, 4 dim green bags" },
{ name: "light fuchsia", contain  : "1 posh aqua bag, 3 posh coral bags" },
{ name: "posh gray", contain  : "5 faded green bags, 5 pale indigo bags, 3 plaid fuchsia bags, 4 faded beige bags" },
{ name: "faded cyan", contain  : "3 dark bronze bags, 1 wavy plum bag" },
{ name: "plaid bronze", contain  : "5 pale silver bags" },
{ name: "dim olive", contain  : "2 shiny gray bags" },
{ name: "faded coral", contain  : "4 wavy blue bags" },
{ name: "pale lime", contain  : "2 dull indigo bags" },
{ name: "dim white", contain  : "4 dotted tan bags, 5 dull indigo bags, 5 plaid red bags, 2 faded silver bags" },
{ name: "muted turquoise", contain  : "1 drab coral bag" },
{ name: "clear bronze", contain  : "5 dark lime bags" },
{ name: "bright plum", contain  : "4 faded coral bags, 2 pale indigo bags, 4 drab salmon bags" },
{ name: "posh orange", contain  : "2 muted brown bags, 1 light white bag, 2 faded blue bags" },
{ name: "muted chartreuse", contain  : "2 pale plum bags, 5 light purple bags" },
{ name: "shiny bronze", contain  : "3 faded turquoise bags, 5 wavy lavender bags" },
{ name: "shiny coral", contain  : "1 wavy coral bag, 5 mirrored olive bags" },
{ name: "posh lavender", contain  : "3 clear gray bags, 5 vibrant white bags" },
{ name: "clear fuchsia", contain  : "4 clear indigo bags, 3 wavy lavender bags, 2 wavy teal bags, 1 clear green bag" },
{ name: "bright tomato", contain  : "3 posh silver bags, 2 wavy beige bags, 4 plaid white bags" },
{ name: "light yellow", contain  : "2 plaid tan bags, 1 plaid purple bag, 3 bright gold bags" },
{ name: "pale magenta", contain  : "3 vibrant turquoise bags" },
{ name: "bright bronze", contain  : "2 shiny gold bags, 4 striped violet bags, 4 striped orange bags, 3 drab green bags" },
{ name: "faded bronze", contain  : "2 dim bronze bags, 4 plaid green bags, 3 light purple bags, 5 striped indigo bags" },
{ name: "plaid coral", contain  : "2 vibrant salmon bags, 4 drab coral bags, 5 light tan bags" },
{ name: "dull coral", contain  : "2 striped coral bags" },
{ name: "muted purple", contain  : "1 bright indigo bag" },
{ name: "light silver", contain  : "3 muted olive bags, 5 drab purple bags, 2 drab lavender bags" },
{ name: "muted aqua", contain  : "5 dull olive bags, 5 drab cyan bags, 5 pale red bags" },
{ name: "posh white", contain  : "4 dim plum bags, 3 wavy blue bags" },
{ name: "dotted olive", contain  : "4 light brown bags" },
{ name: "muted lime", contain  : "4 pale gold bags, 4 dull tan bags" },
{ name: "vibrant magenta", contain  : "3 muted olive bags, 2 drab silver bags, 5 posh purple bags" },
{ name: "dotted coral", contain  : "3 striped turquoise bags, 3 plaid magenta bags, 4 muted cyan bags" },
{ name: "drab green", contain  : "1 drab salmon bag, 3 vibrant purple bags, 3 shiny gold bags, 1 posh silver bag" },
{ name: "vibrant silver", contain  : "5 faded salmon bags" },
{ name: "dull bronze", contain  : "3 light plum bags" },
{ name: "striped coral", contain  : "1 posh brown bag, 4 drab green bags, 1 pale white bag, 1 posh bronze bag" },
{ name: "dim blue", contain  : "2 plaid beige bags, 2 faded gray bags" },
{ name: "mirrored olive", contain  : "2 plaid gray bags, 2 vibrant yellow bags, 3 dim magenta bags" },
{ name: "bright salmon", contain  : "3 bright yellow bags" },
{ name: "bright crimson", contain  : "2 plaid gold bags, 5 bright plum bags" },
{ name: "vibrant yellow", contain  : "1 bright chartreuse bag" },
{ name: "plaid indigo", contain  : "3 wavy silver bags" },
{ name: "bright indigo", contain  : "2 shiny black bags, 1 pale indigo bag" },
{ name: "clear aqua", contain  : "2 drab black bags, 3 clear tan bags, 5 drab purple bags, 1 plaid green bag" },
{ name: "posh tomato", contain  : "3 posh blue bags" },
{ name: "dim tan", contain  : "2 vibrant crimson bags, 4 dark lavender bags, 1 drab orange bag, 1 plaid tomato bag" },
{ name: "dim plum", contain  : "3 vibrant orange bags" },
{ name: "posh teal", contain  : "1 clear salmon bag, 3 light aqua bags" },
{ name: "muted indigo", contain  : "1 mirrored black bag, 1 vibrant purple bag" },
{ name: "dull beige", contain  : "4 bright gray bags, 5 pale silver bags" },
{ name: "dotted cyan", contain  : "4 bright maroon bags, 5 drab cyan bags, 1 bright tomato bag, 4 plaid aqua bags" },
{ name: "faded fuchsia", contain  : "2 light orange bags, 4 clear turquoise bags, 4 pale purple bags, 3 dotted blue bags" },
{ name: "pale bronze", contain  : "1 wavy cyan bag, 2 light silver bags, 1 light magenta bag, 3 plaid chartreuse bags" },
{ name: "dim beige", contain  : "2 striped lavender bags, 2 wavy teal bags, 1 dim plum bag, 4 bright maroon bags" },
{ name: "muted beige", contain  : "4 faded black bags, 4 plaid black bags, 4 clear magenta bags" },
{ name: "dotted lavender", contain  : "5 shiny silver bags, 1 plaid gold bag, 2 wavy lavender bags" },
{ name: "pale green", contain  : "2 pale gold bags" },
{ name: "drab coral", contain  : "1 posh yellow bag, 5 wavy maroon bags, 2 posh chartreuse bags, 2 bright gold bags" },
{ name: "wavy plum", contain  : "1 plaid tan bag, 3 pale black bags, 2 wavy lime bags, 5 pale purple bags" },
{ name: "dotted green", contain  : "1 dark black bag, 4 vibrant yellow bags" },
{ name: "light violet", contain  : "3 faded red bags" },
{ name: "faded gold", contain  : "3 clear teal bags, 2 faded magenta bags" },
{ name: "muted magenta", contain  : "5 striped black bags" },
{ name: "light red", contain  : "3 dark turquoise bags, 2 dim bronze bags" },
{ name: "dim maroon", contain  : "1 dull gold bag, 3 posh yellow bags" },
{ name: "dull fuchsia", contain  : "5 dotted salmon bags, 5 posh gray bags, 5 dark tan bags, 3 dull salmon bags" },
{ name: "wavy gold", contain  : "1 plaid teal bag, 5 light maroon bags" },
{ name: "light coral", contain  : "2 mirrored cyan bags, 3 posh salmon bags, 4 faded red bags" },
{ name: "dark tan", contain  : "3 wavy cyan bags" },
{ name: "faded plum", contain  : "1 dim gold bag, 4 muted crimson bags, 1 mirrored brown bag" },
{ name: "wavy black", contain  : "5 clear green bags" },
{ name: "wavy violet", contain  : "3 bright brown bags" },
{ name: "light teal", contain  : "1 pale olive bag" },
{ name: "posh fuchsia", contain  : "5 bright blue bags, 2 dotted yellow bags, 4 wavy coral bags" },
{ name: "striped violet", contain  : "5 wavy cyan bags, 1 faded lavender bag, 4 shiny silver bags, 2 striped lavender bags" },
{ name: "plaid crimson", contain  : "5 dull chartreuse bags, 2 dark orange bags, 4 pale black bags, 2 light purple bags" },
{ name: "light olive", contain  : "4 dull turquoise bags, 5 dark purple bags, 4 muted chartreuse bags, 3 dark teal bags" },
{ name: "dim magenta", contain  : "5 posh gray bags, 5 vibrant fuchsia bags, 1 posh chartreuse bag" },
{ name: "striped aqua", contain  : "1 pale violet bag, 3 drab lime bags, 1 dark beige bag, 3 light brown bags" },
{ name: "dotted white", contain  : "1 dark gray bag, 1 vibrant orange bag, 5 muted bronze bags, 5 posh gray bags" },
{ name: "faded black", contain  : "1 shiny purple bag, 2 mirrored blue bags, 5 vibrant coral bags, 5 shiny turquoise bags" },
{ name: "dotted black", contain  : "3 drab green bags, 4 plaid beige bags" },
{ name: "dotted gold", contain  : "2 dark bronze bags, 1 drab fuchsia bag" },
{ name: "dark tomato", contain  : "4 dotted plum bags, 4 mirrored crimson bags" },
{ name: "shiny tan", contain  : "2 pale brown bags" },
{ name: "muted gold", contain  : "1 light indigo bag" },
{ name: "dim gold", contain  : "5 light salmon bags" },
{ name: "dull yellow", contain  : "2 striped violet bags" },
{ name: "bright white", contain  : "1 pale black bag" },
{ name: "light purple", contain  : "1 faded salmon bag, 5 dim bronze bags, 3 shiny gray bags, 5 dull teal bags" },
{ name: "shiny magenta", contain  : "5 vibrant blue bags, 4 muted crimson bags, 4 faded white bags" },
{ name: "faded brown", contain  : "2 dotted plum bags, 1 dotted salmon bag" },
{ name: "posh coral", contain  : "5 dark gray bags" },
{ name: "dim green", contain  : "1 light turquoise bag, 2 dark aqua bags, 4 drab magenta bags, 2 faded maroon bags" },
{ name: "dull red", contain  : "5 faded red bags, 3 drab salmon bags, 1 faded blue bag" },
{ name: "clear plum", contain  : "2 dotted tan bags, 3 light blue bags, 3 clear magenta bags, 2 drab green bags" },
{ name: "mirrored lavender", contain  : "1 vibrant purple bag, 1 vibrant plum bag, 2 dark teal bags" },
{ name: "dim salmon", contain  : "5 drab fuchsia bags, 1 drab blue bag" },
{ name: "plaid maroon", contain  : "1 clear violet bag" },
{ name: "dim fuchsia", contain  : "5 dim gold bags, 4 mirrored indigo bags" },
{ name: "dull olive", contain  : "4 faded gray bags, 5 shiny bronze bags" },
{ name: "muted brown", contain  : "1 vibrant coral bag, 3 dark black bags, 4 dotted red bags" },
{ name: "muted lavender", contain  : "3 dim aqua bags, 5 wavy tomato bags" },
{ name: "faded lime", contain  : "4 dim chartreuse bags, 5 drab beige bags" },
{ name: "muted yellow", contain  : "3 dark white bags" },
{ name: "dark purple", contain  : "3 dotted teal bags, 1 wavy tomato bag" },
{ name: "light crimson", contain  : "1 muted cyan bag, 1 pale coral bag" },
{ name: "muted green", contain  : "2 faded plum bags, 2 light chartreuse bags, 4 dull chartreuse bags, 4 vibrant turquoise bags" },
{ name: "vibrant beige", contain  : "3 striped green bags, 1 wavy gold bag, 1 mirrored chartreuse bag" },
{ name: "shiny tomato", contain  : "1 posh bronze bag, 4 pale salmon bags, 4 vibrant orange bags, 1 faded aqua bag" },
{ name: "bright yellow", contain  : "2 dull lavender bags, 3 plaid purple bags, 4 light beige bags, 5 clear indigo bags" },
{ name: "clear black", contain  : "4 dark plum bags" },
{ name: "posh brown", contain  : "5 plaid fuchsia bags, 1 clear turquoise bag, 5 drab white bags" },
{ name: "shiny lime", contain  : "1 light beige bag" },
{ name: "mirrored blue", contain  : "4 drab salmon bags, 4 dim indigo bags" },
{ name: "dull salmon", contain  : "3 drab white bags, 2 vibrant orange bags" },
{ name: "plaid teal", contain  : "no other bags" },
{ name: "plaid blue", contain  : "1 dull indigo bag, 4 wavy black bags, 4 clear red bags" },
];

const examples = [
  { name : "shiny gold" ,contain: "2 dark red bags"},
  { name : "dark red" ,contain: "2 dark orange bags"},
  { name : "dark orange" ,contain: "2 dark yellow bags"},
  { name : "dark yellow" ,contain: "2 dark green bags"},
  { name : "dark green" ,contain: "2 dark blue bags"},
  { name : "dark blue" ,contain: "2 dark violet bags"},
  { name : "dark violet" ,contain: "no other bags"}
  ];


const convertedBags = bags.map(bag=>({
  ...bag,
  contain: bag.contain.split(',').filter(bag=> !bag.includes('no other')).map(bag=>bag.match(/([0-9]{1,2}\s[a-z\s]{1,25})\sbags?/)?.[1]).filter(Boolean),
}))


//543 too hight
//287 right

const result = []

function checkCanContain(colorToFind = 'shiny gold'){
  const res = convertedBags.filter(bag=>bag.contain.some(subBag=>subBag.includes(colorToFind)));
  const named = res.map(bag=>bag.name);
  if(res.length){
    result.push(...res);
    named.forEach(color=>checkCanContain(color));
  }
}

checkCanContain()
// length of the uniq colors
Array.from(new Set(result)).length //?


/**
 * PART 2
 */


const convertedBags2 = examples.map(bag=>({
  ...bag,
  contain: bag.contain.split(',').map(bag=>bag.match(/([0-9]{1,2}\s[a-z\s]{1,25})\sbags?/)?.[1]).filter(Boolean),
}))


let base = 0;
function getNbOfTotalBagForColor(color = 'shiny gold'){
  convertedBags.find(bag=>bag.name === color).contain.map(contain=>{
    if(contain.includes('no other')){
      base++;
    }else{
      const nbIn = contain.match(/[0-9]/)[0]; 
      base+=+nbIn;
      const bagColorIn = contain.match(/[0-9]{1,2}\s([a-z\s]{1,25})?/)?.[1];
      for(let i=0; i< +nbIn; i++){
        getNbOfTotalBagForColor(bagColorIn);
      }
    }
  })
}


getNbOfTotalBagForColor()

base //?
