'use strict';

const exec = [
{ inst: "jmp", arg: +583},
{ inst: "acc" , arg: +9},
{ inst: "jmp" , arg: +525},
{ inst: "jmp" , arg: +302},
{ inst: "jmp" , arg: +287},
{ inst: "jmp" , arg: +412},
{ inst: "acc" , arg: -16},
{ inst: "acc" , arg: -19},
{ inst: "acc" , arg: -19},
{ inst: "jmp" , arg: +423},
{ inst: "acc" , arg: -4},
{ inst: "nop" , arg: +13},
{ inst: "acc" , arg: -8},
{ inst: "jmp" , arg: +37},
{ inst: "acc" , arg: +0},
{ inst: "acc" , arg: -5},
{ inst: "acc" , arg: +48},
{ inst: "acc" , arg: +0},
{ inst: "jmp" , arg: +232},
{ inst: "acc" , arg: +39},
{ inst: "acc" , arg: +5},
{ inst: "jmp" , arg: +69},
{ inst: "acc" , arg: +31},
{ inst: "jmp" , arg: +425},
{ inst: "acc" , arg: +31},
{ inst: "jmp" , arg: +93},
{ inst: "nop" , arg: +166},
{ inst: "acc" , arg: -7},
{ inst: "jmp" , arg: +192},
{ inst: "acc" , arg: +1},
{ inst: "jmp" , arg: +391},
{ inst: "acc" , arg: +11},
{ inst: "acc" , arg: +20},
{ inst: "jmp" , arg: +1},
{ inst: "acc" , arg: +24},
{ inst: "acc" , arg: +7},
{ inst: "acc" , arg: +27},
{ inst: "jmp" , arg: +162},
{ inst: "jmp" , arg: +580},
{ inst: "acc" , arg: +9},
{ inst: "acc" , arg: +39},
{ inst: "acc" , arg: -18},
{ inst: "jmp" , arg: +283},
{ inst: "acc" , arg: +28},
{ inst: "acc" , arg: -14},
{ inst: "nop" , arg: +464},
{ inst: "acc" , arg: -12},
{ inst: "jmp" , arg: +358},
{ inst: "jmp" , arg: +523},
{ inst: "jmp" , arg: +212},
{ inst: "acc" , arg: +16},
{ inst: "acc" , arg: -13},
{ inst: "acc" , arg: +10},
{ inst: "acc" , arg: +46},
{ inst: "jmp" , arg: +207},
{ inst: "jmp" , arg: +266},
{ inst: "jmp" , arg: +1},
{ inst: "acc" , arg: +36},
{ inst: "jmp" , arg: -19},
{ inst: "jmp" , arg: -3},
{ inst: "acc" , arg: -16},
{ inst: "acc" , arg: +3},
{ inst: "jmp" , arg: +229},
{ inst: "acc" , arg: +44},
{ inst: "acc" , arg: +0},
{ inst: "acc" , arg: -17},
{ inst: "acc" , arg: -14},
{ inst: "jmp" , arg: +132},
{ inst: "acc" , arg: +38},
{ inst: "nop" , arg: -30},
{ inst: "acc" , arg: -12},
{ inst: "jmp" , arg: +506},
{ inst: "jmp" , arg: +511},
{ inst: "acc" , arg: -15},
{ inst: "acc" , arg: +4},
{ inst: "acc" , arg: +29},
{ inst: "jmp" , arg: +129},
{ inst: "jmp" , arg: +419},
{ inst: "jmp" , arg: +1},
{ inst: "jmp" , arg: +45},
{ inst: "acc" , arg: +14},
{ inst: "acc" , arg: +20},
{ inst: "acc" , arg: +11},
{ inst: "jmp" , arg: +153},
{ inst: "jmp" , arg: +78},
{ inst: "acc" , arg: +32},
{ inst: "nop" , arg: +212},
{ inst: "acc" , arg: -7},
{ inst: "acc" , arg: +42},
{ inst: "jmp" , arg: -65},
{ inst: "acc" , arg: -17},
{ inst: "jmp" , arg: +458},
{ inst: "acc" , arg: +10},
{ inst: "acc" , arg: +18},
{ inst: "acc" , arg: -11},
{ inst: "acc" , arg: +8},
{ inst: "jmp" , arg: +215},
{ inst: "acc" , arg: +33},
{ inst: "acc" , arg: +25},
{ inst: "jmp" , arg: -21},
{ inst: "nop" , arg: +92},
{ inst: "acc" , arg: +0},
{ inst: "nop" , arg: +353},
{ inst: "jmp" , arg: +188},
{ inst: "acc" , arg: +43},
{ inst: "jmp" , arg: +82},
{ inst: "jmp" , arg: +399},
{ inst: "acc" , arg: +33},
{ inst: "acc" , arg: +16},
{ inst: "acc" , arg: -3},
{ inst: "jmp" , arg: +174},
{ inst: "acc" , arg: -12},
{ inst: "acc" , arg: -3},
{ inst: "nop" , arg: +171},
{ inst: "jmp" , arg: +73},
{ inst: "nop" , arg: +362},
{ inst: "jmp" , arg: -48},
{ inst: "jmp" , arg: +218},
{ inst: "acc" , arg: +5},
{ inst: "jmp" , arg: +486},
{ inst: "acc" , arg: +43},
{ inst: "acc" , arg: -1},
{ inst: "acc" , arg: +0},
{ inst: "jmp" , arg: +476},
{ inst: "acc" , arg: +21},
{ inst: "jmp" , arg: +44},
{ inst: "acc" , arg: +7},
{ inst: "acc" , arg: -6},
{ inst: "jmp" , arg: +1},
{ inst: "acc" , arg: +3},
{ inst: "jmp" , arg: +95},
{ inst: "acc" , arg: +12},
{ inst: "acc" , arg: +38},
{ inst: "jmp" , arg: +202},
{ inst: "acc" , arg: +17},
{ inst: "acc" , arg: -12},
{ inst: "jmp" , arg: +114},
{ inst: "jmp" , arg: -33},
{ inst: "jmp" , arg: +367},
{ inst: "acc" , arg: +45},
{ inst: "acc" , arg: +40},
{ inst: "jmp" , arg: -81},
{ inst: "acc" , arg: -5},
{ inst: "acc" , arg: +27},
{ inst: "acc" , arg: +6},
{ inst: "jmp" , arg: +374},
{ inst: "acc" , arg: -6},
{ inst: "acc" , arg: +10},
{ inst: "acc" , arg: +19},
{ inst: "jmp" , arg: +1},
{ inst: "jmp" , arg: +171},
{ inst: "acc" , arg: +8},
{ inst: "acc" , arg: +46},
{ inst: "acc" , arg: +12},
{ inst: "jmp" , arg: +234},
{ inst: "acc" , arg: +45},
{ inst: "acc" , arg: +28},
{ inst: "jmp" , arg: +337},
{ inst: "acc" , arg: +8},
{ inst: "nop" , arg: +10},
{ inst: "acc" , arg: +17},
{ inst: "jmp" , arg: +368},
{ inst: "acc" , arg: +2},
{ inst: "acc" , arg: -3},
{ inst: "acc" , arg: +29},
{ inst: "jmp" , arg: -160},
{ inst: "acc" , arg: -7},
{ inst: "acc" , arg: +11},
{ inst: "jmp" , arg: +174},
{ inst: "acc" , arg: +48},
{ inst: "acc" , arg: -3},
{ inst: "acc" , arg: +33},
{ inst: "jmp" , arg: +6},
{ inst: "acc" , arg: +3},
{ inst: "acc" , arg: -10},
{ inst: "acc" , arg: +9},
{ inst: "acc" , arg: -13},
{ inst: "jmp" , arg: +428},
{ inst: "acc" , arg: -13},
{ inst: "acc" , arg: +35},
{ inst: "nop" , arg: -112},
{ inst: "jmp" , arg: -147},
{ inst: "acc" , arg: +13},
{ inst: "acc" , arg: -4},
{ inst: "acc" , arg: +50},
{ inst: "acc" , arg: +46},
{ inst: "jmp" , arg: -118},
{ inst: "acc" , arg: +38},
{ inst: "acc" , arg: +36},
{ inst: "jmp" , arg: +375},
{ inst: "nop" , arg: -3},
{ inst: "jmp" , arg: +93},
{ inst: "acc" , arg: +10},
{ inst: "acc" , arg: -1},
{ inst: "jmp" , arg: +211},
{ inst: "acc" , arg: +6},
{ inst: "acc" , arg: +38},
{ inst: "acc" , arg: -12},
{ inst: "jmp" , arg: -6},
{ inst: "jmp" , arg: +1},
{ inst: "acc" , arg: +41},
{ inst: "jmp" , arg: -117},
{ inst: "acc" , arg: -17},
{ inst: "acc" , arg: -15},
{ inst: "jmp" , arg: -120},
{ inst: "acc" , arg: +17},
{ inst: "acc" , arg: +48},
{ inst: "acc" , arg: +37},
{ inst: "acc" , arg: +0},
{ inst: "jmp" , arg: +139},
{ inst: "acc" , arg: +7},
{ inst: "acc" , arg: -12},
{ inst: "acc" , arg: +0},
{ inst: "jmp" , arg: +98},
{ inst: "acc" , arg: +47},
{ inst: "acc" , arg: +3},
{ inst: "acc" , arg: -18},
{ inst: "acc" , arg: +26},
{ inst: "jmp" , arg: +141},
{ inst: "jmp" , arg: +236},
{ inst: "acc" , arg: +18},
{ inst: "jmp" , arg: +275},
{ inst: "acc" , arg: -10},
{ inst: "acc" , arg: -11},
{ inst: "jmp" , arg: +12},
{ inst: "acc" , arg: -19},
{ inst: "acc" , arg: +17},
{ inst: "jmp" , arg: +300},
{ inst: "acc" , arg: +32},
{ inst: "nop" , arg: +145},
{ inst: "jmp" , arg: +84},
{ inst: "jmp" , arg: +34},
{ inst: "acc" , arg: -17},
{ inst: "acc" , arg: +12},
{ inst: "acc" , arg: +37},
{ inst: "jmp" , arg: +182},
{ inst: "acc" , arg: -7},
{ inst: "jmp" , arg: +154},
{ inst: "nop" , arg: +375},
{ inst: "acc" , arg: -1},
{ inst: "jmp" , arg: +108},
{ inst: "jmp" , arg: +1},
{ inst: "acc" , arg: +16},
{ inst: "acc" , arg: +49},
{ inst: "jmp" , arg: +355},
{ inst: "acc" , arg: -16},
{ inst: "acc" , arg: -19},
{ inst: "acc" , arg: +47},
{ inst: "acc" , arg: +26},
{ inst: "jmp" , arg: -171},
{ inst: "jmp" , arg: +285},
{ inst: "jmp" , arg: +84},
{ inst: "acc" , arg: +28},
{ inst: "acc" , arg: -11},
{ inst: "acc" , arg: +6},
{ inst: "jmp" , arg: -252},
{ inst: "nop" , arg: +228},
{ inst: "acc" , arg: +10},
{ inst: "acc" , arg: -17},
{ inst: "acc" , arg: +42},
{ inst: "jmp" , arg: -221},
{ inst: "acc" , arg: +34},
{ inst: "acc" , arg: +8},
{ inst: "jmp" , arg: +201},
{ inst: "jmp" , arg: -225},
{ inst: "acc" , arg: +45},
{ inst: "nop" , arg: +125},
{ inst: "acc" , arg: +25},
{ inst: "acc" , arg: -7},
{ inst: "jmp" , arg: +318},
{ inst: "nop" , arg: +348},
{ inst: "nop" , arg: +40},
{ inst: "acc" , arg: +42},
{ inst: "jmp" , arg: +284},
{ inst: "acc" , arg: -1},
{ inst: "acc" , arg: +46},
{ inst: "jmp" , arg: +1},
{ inst: "acc" , arg: +41},
{ inst: "jmp" , arg: +231},
{ inst: "acc" , arg: +30},
{ inst: "acc" , arg: +45},
{ inst: "acc" , arg: +10},
{ inst: "acc" , arg: +45},
{ inst: "jmp" , arg: -227},
{ inst: "acc" , arg: +25},
{ inst: "acc" , arg: +13},
{ inst: "jmp" , arg: +219},
{ inst: "acc" , arg: -10},
{ inst: "acc" , arg: +27},
{ inst: "acc" , arg: +45},
{ inst: "jmp" , arg: -186},
{ inst: "acc" , arg: -18},
{ inst: "acc" , arg: +50},
{ inst: "acc" , arg: +31},
{ inst: "acc" , arg: +19},
{ inst: "jmp" , arg: +89},
{ inst: "nop" , arg: -240},
{ inst: "jmp" , arg: +173},
{ inst: "nop" , arg: +65},
{ inst: "acc" , arg: -8},
{ inst: "jmp" , arg: +1},
{ inst: "nop" , arg: -146},
{ inst: "jmp" , arg: -156},
{ inst: "acc" , arg: +27},
{ inst: "jmp" , arg: +106},
{ inst: "acc" , arg: +4},
{ inst: "acc" , arg: +45},
{ inst: "jmp" , arg: +35},
{ inst: "acc" , arg: +44},
{ inst: "acc" , arg: +47},
{ inst: "jmp" , arg: -254},
{ inst: "jmp" , arg: +57},
{ inst: "acc" , arg: +1},
{ inst: "jmp" , arg: -274},
{ inst: "acc" , arg: +32},
{ inst: "acc" , arg: +6},
{ inst: "acc" , arg: +1},
{ inst: "nop" , arg: +179},
{ inst: "jmp" , arg: +122},
{ inst: "jmp" , arg: +1},
{ inst: "jmp" , arg: -310},
{ inst: "jmp" , arg: -273},
{ inst: "acc" , arg: +46},
{ inst: "acc" , arg: +9},
{ inst: "jmp" , arg: -187},
{ inst: "acc" , arg: +36},
{ inst: "acc" , arg: +0},
{ inst: "nop" , arg: +47},
{ inst: "acc" , arg: +17},
{ inst: "jmp" , arg: -137},
{ inst: "nop" , arg: -116},
{ inst: "acc" , arg: -17},
{ inst: "acc" , arg: -6},
{ inst: "acc" , arg: -8},
{ inst: "jmp" , arg: +106},
{ inst: "acc" , arg: +36},
{ inst: "acc" , arg: +50},
{ inst: "acc" , arg: +3},
{ inst: "acc" , arg: +22},
{ inst: "jmp" , arg: +190},
{ inst: "acc" , arg: +48},
{ inst: "jmp" , arg: -336},
{ inst: "jmp" , arg: -164},
{ inst: "jmp" , arg: -32},
{ inst: "acc" , arg: +44},
{ inst: "nop" , arg: +242},
{ inst: "jmp" , arg: -215},
{ inst: "jmp" , arg: +7},
{ inst: "acc" , arg: +36},
{ inst: "acc" , arg: +3},
{ inst: "acc" , arg: +27},
{ inst: "acc" , arg: +24},
{ inst: "jmp" , arg: -8},
{ inst: "jmp" , arg: +156},
{ inst: "acc" , arg: -5},
{ inst: "acc" , arg: +42},
{ inst: "nop" , arg: +37},
{ inst: "jmp" , arg: +107},
{ inst: "jmp" , arg: +247},
{ inst: "acc" , arg: +12},
{ inst: "acc" , arg: +30},
{ inst: "jmp" , arg: +44},
{ inst: "jmp" , arg: -306},
{ inst: "acc" , arg: +36},
{ inst: "jmp" , arg: -354},
{ inst: "nop" , arg: +192},
{ inst: "nop" , arg: +153},
{ inst: "jmp" , arg: -106},
{ inst: "jmp" , arg: -284},
{ inst: "jmp" , arg: +1},
{ inst: "acc" , arg: +33},
{ inst: "acc" , arg: +18},
{ inst: "acc" , arg: +13},
{ inst: "jmp" , arg: +232},
{ inst: "acc" , arg: -4},
{ inst: "nop" , arg: -64},
{ inst: "acc" , arg: +38},
{ inst: "acc" , arg: +29},
{ inst: "jmp" , arg: -349},
{ inst: "acc" , arg: -7},
{ inst: "acc" , arg: +44},
{ inst: "acc" , arg: +4},
{ inst: "acc" , arg: +48},
{ inst: "jmp" , arg: -35},
{ inst: "acc" , arg: +13},
{ inst: "jmp" , arg: -144},
{ inst: "acc" , arg: -7},
{ inst: "jmp" , arg: +196},
{ inst: "acc" , arg: -8},
{ inst: "jmp" , arg: -316},
{ inst: "jmp" , arg: -138},
{ inst: "jmp" , arg: -381},
{ inst: "jmp" , arg: -156},
{ inst: "acc" , arg: +21},
{ inst: "jmp" , arg: +189},
{ inst: "acc" , arg: +30},
{ inst: "nop" , arg: -85},
{ inst: "acc" , arg: +34},
{ inst: "acc" , arg: -13},
{ inst: "jmp" , arg: -326},
{ inst: "jmp" , arg: -7},
{ inst: "jmp" , arg: +1},
{ inst: "acc" , arg: +2},
{ inst: "acc" , arg: +24},
{ inst: "jmp" , arg: -56},
{ inst: "jmp" , arg: +152},
{ inst: "acc" , arg: +42},
{ inst: "acc" , arg: +25},
{ inst: "acc" , arg: -6},
{ inst: "jmp" , arg: +174},
{ inst: "jmp" , arg: -96},
{ inst: "jmp" , arg: -86},
{ inst: "jmp" , arg: +20},
{ inst: "acc" , arg: +23},
{ inst: "nop" , arg: -93},
{ inst: "acc" , arg: +3},
{ inst: "jmp" , arg: -42},
{ inst: "acc" , arg: +0},
{ inst: "acc" , arg: +6},
{ inst: "jmp" , arg: +100},
{ inst: "jmp" , arg: +20},
{ inst: "jmp" , arg: -147},
{ inst: "acc" , arg: +19},
{ inst: "nop" , arg: -367},
{ inst: "jmp" , arg: -80},
{ inst: "nop" , arg: -318},
{ inst: "nop" , arg: -289},
{ inst: "acc" , arg: +45},
{ inst: "jmp" , arg: -321},
{ inst: "nop" , arg: -4},
{ inst: "acc" , arg: +13},
{ inst: "jmp" , arg: +74},
{ inst: "acc" , arg: +0},
{ inst: "acc" , arg: +15},
{ inst: "jmp" , arg: +153},
{ inst: "acc" , arg: -5},
{ inst: "acc" , arg: +24},
{ inst: "acc" , arg: +21},
{ inst: "jmp" , arg: +1},
{ inst: "jmp" , arg: -48},
{ inst: "jmp" , arg: -262},
{ inst: "nop" , arg: -317},
{ inst: "jmp" , arg: +93},
{ inst: "acc" , arg: +20},
{ inst: "jmp" , arg: -32},
{ inst: "acc" , arg: +44},
{ inst: "acc" , arg: +50},
{ inst: "jmp" , arg: -350},
{ inst: "acc" , arg: -19},
{ inst: "acc" , arg: +46},
{ inst: "jmp" , arg: -431},
{ inst: "acc" , arg: -11},
{ inst: "nop" , arg: -227},
{ inst: "acc" , arg: +48},
{ inst: "jmp" , arg: +103},
{ inst: "acc" , arg: +44},
{ inst: "acc" , arg: +31},
{ inst: "acc" , arg: -15},
{ inst: "jmp" , arg: -15},
{ inst: "acc" , arg: +0},
{ inst: "acc" , arg: +34},
{ inst: "acc" , arg: -3},
{ inst: "acc" , arg: +38},
{ inst: "jmp" , arg: +108},
{ inst: "acc" , arg: +28},
{ inst: "nop" , arg: -60},
{ inst: "acc" , arg: +28},
{ inst: "acc" , arg: +26},
{ inst: "jmp" , arg: -20},
{ inst: "jmp" , arg: -440},
{ inst: "acc" , arg: +48},
{ inst: "jmp" , arg: -257},
{ inst: "acc" , arg: +11},
{ inst: "acc" , arg: +8},
{ inst: "acc" , arg: +14},
{ inst: "acc" , arg: +30},
{ inst: "jmp" , arg: +8},
{ inst: "acc" , arg: +47},
{ inst: "jmp" , arg: -323},
{ inst: "acc" , arg: +15},
{ inst: "acc" , arg: +10},
{ inst: "acc" , arg: -15},
{ inst: "acc" , arg: +13},
{ inst: "jmp" , arg: -169},
{ inst: "acc" , arg: -11},
{ inst: "acc" , arg: -12},
{ inst: "acc" , arg: +24},
{ inst: "acc" , arg: +5},
{ inst: "jmp" , arg: +125},
{ inst: "acc" , arg: +34},
{ inst: "acc" , arg: -17},
{ inst: "acc" , arg: +2},
{ inst: "acc" , arg: +32},
{ inst: "jmp" , arg: -83},
{ inst: "jmp" , arg: -120},
{ inst: "jmp" , arg: -11},
{ inst: "acc" , arg: +25},
{ inst: "nop" , arg: -54},
{ inst: "jmp" , arg: +1},
{ inst: "jmp" , arg: -29},
{ inst: "acc" , arg: +13},
{ inst: "acc" , arg: +17},
{ inst: "acc" , arg: +6},
{ inst: "acc" , arg: +31},
{ inst: "jmp" , arg: -420},
{ inst: "acc" , arg: +25},
{ inst: "acc" , arg: +13},
{ inst: "jmp" , arg: +117},
{ inst: "jmp" , arg: -3},
{ inst: "nop" , arg: +68},
{ inst: "acc" , arg: +32},
{ inst: "acc" , arg: -11},
{ inst: "acc" , arg: +31},
{ inst: "jmp" , arg: -374},
{ inst: "acc" , arg: -4},
{ inst: "acc" , arg: +34},
{ inst: "acc" , arg: +38},
{ inst: "acc" , arg: +23},
{ inst: "jmp" , arg: -113},
{ inst: "acc" , arg: -19},
{ inst: "acc" , arg: +50},
{ inst: "nop" , arg: -216},
{ inst: "jmp" , arg: -134},
{ inst: "nop" , arg: -331},
{ inst: "acc" , arg: -7},
{ inst: "acc" , arg: +28},
{ inst: "jmp" , arg: -357},
{ inst: "jmp" , arg: -216},
{ inst: "jmp" , arg: -128},
{ inst: "acc" , arg: +34},
{ inst: "acc" , arg: +16},
{ inst: "jmp" , arg: -54},
{ inst: "acc" , arg: -16},
{ inst: "acc" , arg: +0},
{ inst: "jmp" , arg: -64},
{ inst: "acc" , arg: +7},
{ inst: "nop" , arg: -322},
{ inst: "jmp" , arg: -306},
{ inst: "nop" , arg: -414},
{ inst: "acc" , arg: +38},
{ inst: "acc" , arg: +15},
{ inst: "jmp" , arg: +77},
{ inst: "acc" , arg: +18},
{ inst: "jmp" , arg: +1},
{ inst: "acc" , arg: +0},
{ inst: "acc" , arg: -8},
{ inst: "jmp" , arg: -248},
{ inst: "acc" , arg: +26},
{ inst: "jmp" , arg: -6},
{ inst: "acc" , arg: +17},
{ inst: "acc" , arg: +21},
{ inst: "acc" , arg: +30},
{ inst: "jmp" , arg: -142},
{ inst: "acc" , arg: -13},
{ inst: "acc" , arg: -18},
{ inst: "nop" , arg: -330},
{ inst: "jmp" , arg: +27},
{ inst: "acc" , arg: -14},
{ inst: "jmp" , arg: +60},
{ inst: "acc" , arg: +31},
{ inst: "acc" , arg: -6},
{ inst: "acc" , arg: +49},
{ inst: "acc" , arg: +16},
{ inst: "jmp" , arg: -289},
{ inst: "acc" , arg: +11},
{ inst: "acc" , arg: +0},
{ inst: "nop" , arg: -141},
{ inst: "acc" , arg: +19},
{ inst: "jmp" , arg: -143},
{ inst: "acc" , arg: +44},
{ inst: "jmp" , arg: -286},
{ inst: "acc" , arg: +42},
{ inst: "jmp" , arg: -209},
{ inst: "acc" , arg: +34},
{ inst: "acc" , arg: +10},
{ inst: "acc" , arg: +3},
{ inst: "jmp" , arg: -461},
{ inst: "acc" , arg: +2},
{ inst: "jmp" , arg: -358},
{ inst: "acc" , arg: +42},
{ inst: "acc" , arg: +0},
{ inst: "acc" , arg: +26},
{ inst: "jmp" , arg: -191},
{ inst: "acc" , arg: +16},
{ inst: "jmp" , arg: -230},
{ inst: "acc" , arg: +31},
{ inst: "jmp" , arg: -244},
{ inst: "nop" , arg: -456},
{ inst: "acc" , arg: +16},
{ inst: "nop" , arg: -196},
{ inst: "jmp" , arg: -475},
{ inst: "acc" , arg: +24},
{ inst: "jmp" , arg: -553},
{ inst: "acc" , arg: +42},
{ inst: "acc" , arg: +24},
{ inst: "acc" , arg: +3},
{ inst: "jmp" , arg: -572},
{ inst: "acc" , arg: +31},
{ inst: "jmp" , arg: +7},
{ inst: "jmp" , arg: -144},
{ inst: "acc" , arg: +20},
{ inst: "acc" , arg: +23},
{ inst: "acc" , arg: -14},
{ inst: "nop" , arg: -506},
{ inst: "jmp" , arg: -17},
{ inst: "acc" , arg: +19},
{ inst: "nop" , arg: -428},
{ inst: "jmp" , arg: -286},
{ inst: "acc" , arg: +2},
{ inst: "acc" , arg: +6},
{ inst: "acc" , arg: +28},
{ inst: "acc" , arg: -13},
{ inst: "jmp" , arg: -291},
{ inst: "jmp" , arg: -377},
{ inst: "acc" , arg: -3},
{ inst: "acc" , arg: +32},
{ inst: "jmp" , arg: +1},
{ inst: "jmp" , arg: -205},
{ inst: "acc" , arg: +18},
{ inst: "acc" , arg: +32},
{ inst: "nop" , arg: -523},
{ inst: "jmp" , arg: -79},
{ inst: "acc" , arg: +32},
{ inst: "jmp" , arg: -30},
{ inst: "acc" , arg: +40},
{ inst: "acc" , arg: -17},
{ inst: "jmp" , arg: +1},
{ inst: "acc" , arg: +28},
{ inst: "jmp" , arg: +1},
];

function execution(acc = 0, currentLine = 0, readLines = new Map(), debugged = 0): any{
  if(readLines.has(currentLine)) {
    throw new Error('Hit the loop' + currentLine + ' ' + acc);
  }
  readLines.set(currentLine, exec[currentLine]);
  if(exec[currentLine].inst === "acc"){
    acc+= exec[currentLine].arg;
    currentLine++;
  }
  if(exec[currentLine].inst == "jmp"){
    currentLine += exec[currentLine].arg
  }
  if(exec[currentLine].inst == "nop"){
    currentLine++;
  }
  return execution(acc,currentLine, readLines, debugged)
}

execution();

/**
 * PART 2
 */
let finished = false;
let acc = 0;
let currentLine = 0;
let readLines = new Map();
let debugged = 0;

let execCopy = exec.map(ex=>({
  ...ex
}));

do{
  if(currentLine === execCopy.length-1){
    console.log('finished')
    finished = true;
    break;
  }
  if(readLines.has(currentLine)) {
    execCopy = exec.map(ex=>({
      ...ex
    }));
    if(execCopy[debugged].inst !== 'acc'){
      execCopy[debugged] = {...execCopy[debugged], inst: execCopy[debugged].inst === 'jmp' ? 'nop': 'jmp' }
    }
    debugged++;
    acc =0;
    currentLine =0;
    readLines=new Map();
    continue;
  }
  readLines.set(currentLine, execCopy[currentLine]);
  if(execCopy[currentLine].inst === "acc"){
    acc+= execCopy[currentLine].arg;
    currentLine++;
  }
  else if(execCopy[currentLine].inst === "jmp"){
    currentLine += execCopy[currentLine].arg
  }
  else if(execCopy[currentLine].inst === "nop"){
    currentLine++;
  }
}while(!finished)

console.log(acc) //?
